--Find total customers by countries
SELECT
country,
COUNT(customer_key) AS customers_per_country
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_id) DESC

--Find total customers by gender
SELECT
gender,
COUNT(customer_id) AS customers_per_country
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_id) DESC

--Find total products by category
SELECT
category,
COUNT(product_id) _total_products_cat
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_id) DESC

--What is the average cost in each category
SELECT
category,
AVG(cost) avg_cost_category
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC

--What is the total revenue generated in each category
SELECT
p.category,
SUM(s.sales_amount) revenue_category 
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS s
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY revenue_category DESC

--Find total revenue generated by each customer
SELECT
DISTINCT customer_key,
SUM(sales_amount)
FROM gold.fact_sales
GROUP BY customer_key
ORDER BY SUM(sales_amount) DESC


--What is the distribution of sold items across countries
SELECT
c.country,
SUM(s.sales_amount) total_sold_items 
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items  DESC